parameters: {}
environment: {}
packages:
    - name: wishes
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: ima
          binary: false
          main: ""
          runtime: php:8.2
          web: true
          webSecure: false
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}
        - name: meenah
          binary: false
          main: ""
          runtime: nodejs:14
          web: true
          webSecure: false
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}
